#!/bin/sh
sudo chmod +x ./script/deploy
sudo ssh ubuntu@3.108.195.199 <<EOF
    cd ~/Book_Store
    sudo git pull origin main
    sudo curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh|bash
    sudo . ~/.nvm/nvm.sh
    sudo nvm install v10.11.0
    sudo npm install
    sudo npm install -g nodemon pm2
    sudo pm2 restart ecosystem.config.js
    sudo npm audit fix
    exit
EOF